export default [
  {
    name: "Test",
    producer: "metro-boomin",
    pattern: [
      [
        { active: true },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: true },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false }
      ],
      [
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false }
      ],
      [
        { active: true },
        { active: true },
        { active: true },
        { active: true },
        { active: true },
        { active: true },
        { active: true },
        { active: true },
        { active: true },
        { active: true },
        { active: false },
        { active: false },
        { active: true },
        { active: true },
        { active: true },
        { active: false },
        { active: true },
        { active: true },
        { active: true },
        { active: true },
        { active: true },
        { active: true },
        { active: true },
        { active: true }
      ],
      [
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: true },
        { active: false },
        { active: true },
        { active: false },
        { active: false },
        { active: false },
        { active: true },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false }
      ],
      [
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false }
      ],
      [
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false }
      ],
      [
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: true },
        { active: false },
        { active: true },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false }
      ],
      [
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: true },
        { active: true },
        { active: false },
        { active: true },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: true },
        { active: true },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false }
      ],
      [
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false },
        { active: false }
      ]
    ],
    tracksStates: [
      {
        mute: false,
        solo: false,
        volume: 0
      },
      {
        mute: false,
        solo: false,
        volume: -3
      },
      {
        mute: false,
        solo: false,
        volume: -6
      },
      {
        mute: false,
        solo: false,
        volume: -3
      },
      {
        mute: false,
        solo: false,
        volume: -3
      },
      {
        mute: false,
        solo: false,
        volume: -3
      },
      {
        mute: false,
        solo: false,
        volume: -3
      },
      {
        mute: false,
        solo: false,
        volume: -3
      },
      {
        mute: false,
        solo: false,
        volume: -3
      }
    ],
    tempo: 105
  }
];
